

version: '3.8'

services:

  makara-spring:
    container_name: 'Spring_elastic_search_suggestion'
#    depends_on:
#      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://136.228.158.126:3125
      - ELASTICSEARCH_HOSTS=http://136.228.158.126:3125
      - ELASTICSEARCH_USERNAME=elastic
    ports:
      - '3127:8888'
    volumes:
      - '/myproject:/home/ite/media'
#    networks:
#      - elastic8
#  pgsync-python:
#    build: ../../Test-in-local-elastic/spring_elastic_search_user/pgsync-python
#    container_name: pgsync-python
##    depends_on:
##      - elasticsearch
#    volumes:
#      - ./pgsync-python:/app
##    networks:
##      - elastic8

#
#
#  kibana:
#   image: docker.elastic.co/kibana/kibana:7.8.0
#   container_name: kibana1
#   depends_on:
#    - elasticsearch
#   environment:
#    - ELASTICSEARCH_URL=http://elasticsearch:9200
#    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    - ELASTICSEARCH_USERNAME=elastic
#    - xpack.monitoring.ui.container.elasticsearch.enabled=true
#   ports:
#    - "5601:5601"
#   networks:
#    - elastic8
#
#  elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
#   container_name: elasticsearch
#   environment:
#    - discovery.type=single-node
#   ports:
#    - "9200:9200"
#
#   volumes:
#    - esdata:/usr/share/elasticsearch/data
#   networks:
#    - elastic8
#
#
volumes:
  esdata:
#
#networks:
#  elastic8:
#    driver: bridge

